name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Clean install dependencies
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm install
        npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Verify build output
      run: |
        echo "Checking dist directory contents..."
        ls -la dist/
        echo "Checking for index.html..."
        test -f dist/index.html && echo "✓ index.html exists" || echo "✗ index.html missing"
        echo "Checking for assets..."
        test -d dist/assets && echo "✓ assets directory exists" || echo "✗ assets directory missing"
    
    - name: Prepare deployment directory on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Create backup of current deployment (if user has permissions)
          if [ -d /var/www/jonieshorsecare.nl ]; then
            cp -r /var/www/jonieshorsecare.nl /var/www/jonieshorsecare.nl.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || echo "Skipping backup (no permissions)"
          fi
          
          # Ensure directory exists and is writable
          mkdir -p /var/www/jonieshorsecare.nl
          
          # Clean old backups (keep last 3) - only if user has permissions
          ls -t /var/www/jonieshorsecare.nl.backup.* 2>/dev/null | tail -n +4 | xargs -r rm -rf 2>/dev/null || echo "Skipping backup cleanup"
    
    - name: Deploy built files via rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.git' --exclude='node_modules' --exclude='.github'
        path: dist/
        remote_path: /var/www/jonieshorsecare.nl/
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
        remote_port: ${{ secrets.PORT }}
        
    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Verify critical files exist
          echo "Verifying deployment..."
          test -f /var/www/jonieshorsecare.nl/index.html && echo "✓ index.html deployed" || echo "✗ index.html missing!"
          test -d /var/www/jonieshorsecare.nl/assets && echo "✓ assets directory deployed" || echo "✗ assets directory missing!"
          
          # Show directory structure
          echo "Deployment structure:"
          ls -lah /var/www/jonieshorsecare.nl/ | head -20
          
          # Check permissions
          echo "Current permissions:"
          ls -ld /var/www/jonieshorsecare.nl/