name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Verify build output
      run: |
        echo "Checking dist directory contents..."
        ls -la dist/
        echo "Checking for index.html..."
        test -f dist/index.html && echo "✓ index.html exists" || echo "✗ index.html missing"
        echo "Checking for assets..."
        test -d dist/assets && echo "✓ assets directory exists" || echo "✗ assets directory missing"
    
    - name: Prepare deployment directory on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Create backup of current deployment
          if [ -d /home/deploy/static-sites/jonieshorsecare.nl ]; then
            sudo cp -r /home/deploy/static-sites/jonieshorsecare.nl /home/deploy/static-sites/jonieshorsecare.nl.backup
          fi
          
          # Ensure directory exists
          sudo mkdir -p /home/deploy/static-sites/jonieshorsecare.nl
          sudo chown -R deploy:deploy /home/deploy/static-sites/jonieshorsecare.nl
    
    - name: Deploy built files via rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.git' --exclude='node_modules' --exclude='.github'
        path: dist/
        remote_path: /home/deploy/static-sites/jonieshorsecare.nl/
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
        remote_port: ${{ secrets.PORT }}
        
    - name: Set proper permissions and verify deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Set proper ownership and permissions
          sudo chown -R www-data:www-data /var/www/jonieshorsecare.nl/
          sudo find /var/www/jonieshorsecare.nl/ -type d -exec chmod 755 {} \;
          sudo find /var/www/jonieshorsecare.nl/ -type f -exec chmod 644 {} \;
          
          # Verify critical files exist
          echo "Verifying deployment..."
          test -f /var/www/jonieshorsecare.nl/index.html && echo "✓ index.html deployed" || echo "✗ index.html missing!"
          test -d /var/www/jonieshorsecare.nl/assets && echo "✓ assets directory deployed" || echo "✗ assets directory missing!"
          
          # Show directory structure
          echo "Deployment structure:"
          ls -lah /var/www/jonieshorsecare.nl/ | head -20