name: Deploy Static Site

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Prepare deployment directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Ensure the deployment directory structure exists
          mkdir -p /home/deploy/static-sites/jonieshorsecare.nl/images
          chmod -R 755 /home/deploy/static-sites/jonieshorsecare.nl
          echo "Directory created and permissions set"
          ls -la /home/deploy/static-sites/jonieshorsecare.nl/
          
    - name: Deploy via rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.git' --exclude='node_modules' --exclude='.github'
        path: ./
        remote_path: /home/deploy/static-sites/jonieshorsecare.nl/
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
        remote_port: ${{ secrets.PORT }}
        
    - name: Set proper permissions
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Set proper ownership and permissions for web files (without sudo since deploy user owns the files)
          chown -R deploy:www-data /home/deploy/static-sites/jonieshorsecare.nl/ || echo "chown failed, but continuing"
          find /home/deploy/static-sites/jonieshorsecare.nl/ -type d -exec chmod 755 {} \; || echo "chmod dirs failed, but continuing"
          find /home/deploy/static-sites/jonieshorsecare.nl/ -type f -exec chmod 644 {} \; || echo "chmod files failed, but continuing"
          echo "Permissions set (with possible warnings above)"
          ls -la /home/deploy/static-sites/jonieshorsecare.nl/